[package]
name = "rust-json"
version = "0.0.1"
authors = ["Sdogruyol <dogruyolserdar@gmail.com>"]

[dependencies.nickel]
git = "https://github.com/nickel-org/nickel.rs.git"

[dependencies]
rustc-serialize = "*"
